name: flutter_auth

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  #supabase: ^0.2.15
  #supabase_flutter: ^0.2.12
  google_sign_in: ^5.2.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
